"""pages and users

Revision ID: 1771901598
Revises:
Create Date: 2026-02-24 02:53:18.208841

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1771901598"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = ("default",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("parent_category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["categories.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_type", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("group", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metadata_group"), "metadata", ["group"], unique=False)
    op.create_index(op.f("ix_metadata_key"), "metadata", ["key"], unique=False)
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("redirect_to", sa.Integer(), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["redirect_to"], ["pages.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("current_version_id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_pages_namespace"), "pages", ["namespace"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "category_page",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("category_id", "page_id"),
    )
    op.create_table(
        "changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("object_type", sa.String(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interlinks",
        sa.Column("likes_from_id", sa.Integer(), nullable=False),
        sa.Column("links_to_title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["likes_from_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("likes_from_id", "links_to_title"),
    )
    op.create_table(
        "revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("constructed_hash", sa.String(), nullable=False),
        sa.Column("parent_hash", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("base_content", sa.LargeBinary(), nullable=False),
        sa.Column("delta", sa.LargeBinary(), nullable=False),
        sa.Column("draft", sa.Boolean(), nullable=False),
        sa.Column("imported", sa.Boolean(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("change", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["revisions.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("revisions")
    op.drop_table("interlinks")
    op.drop_table("changes")
    op.drop_table("category_page")
    op.drop_table("users")
    op.drop_index(op.f("ix_pages_namespace"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_metadata_key"), table_name="metadata")
    op.drop_index(op.f("ix_metadata_group"), table_name="metadata")
    op.drop_table("metadata")
    op.drop_table("categories")
    # ### end Alembic commands ###
