"""Pages

Revision ID: 1771682494
Revises: 1771681763
Create Date: 2026-02-21 14:01:34.443443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1771682494"
down_revision: Union[str, Sequence[str], None] = "1771681763"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("parent_category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["categories.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("redirect_to", sa.Integer(), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["redirect_to"], ["pages.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("current_version_id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_pages_namespace"), "pages", ["namespace"], unique=False)
    op.create_table(
        "category_page",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.PrimaryKeyConstraint("category_id", "page_id"),
    )
    op.create_table(
        "interlinks",
        sa.Column("likes_from_id", sa.Integer(), nullable=False),
        sa.Column("links_to_title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["likes_from_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("likes_from_id", "links_to_title"),
    )
    op.create_table(
        "revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("constructed_hash", sa.String(), nullable=False),
        sa.Column("parent_hash", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("base_content", sa.LargeBinary(), nullable=False),
        sa.Column("delta", sa.LargeBinary(), nullable=False),
        sa.Column("draft", sa.Boolean(), nullable=False),
        sa.Column("imported", sa.Boolean(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("change", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["revisions.id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("revisions")
    op.drop_table("interlinks")
    op.drop_table("category_page")
    op.drop_index(op.f("ix_pages_namespace"), table_name="pages")
    op.drop_table("pages")
    op.drop_table("categories")
    # ### end Alembic commands ###
